{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wrswor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wrswoR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wrswoR/wrswoR_{{ version }}.tar.gz
  sha256: 11045a62feef679bbcb02a0ede8a2c5985393df57f47b67da2733884116016e0

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-logging                    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >= 0.11.5
    - r-logging >=0.4_13
  run:
    - r-base
    - r-rcpp
    - r-logging >=0.4_13

test:
  commands:
    - $R -e "library('wrswoR')"           # [not win]
    - "\"%R%\" -e \"library('wrswoR')\""  # [win]

about:
  home: https://krlmlr.github.io/wrswoR/
  dev_url: https://github.com/krlmlr/wrswoR/
  doc_url: https://krlmlr.github.io/wrswoR/reference/index.html
  license: GPL-3.0-only
  summary: A collection of implementations of classical and novel algorithms for weighted sampling
    without replacement.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
